import assert from 'node:assert/strict';
import { after, before, describe, it } from 'node:test';
import http from 'node:http';

const STUB_PORT = 8991;
process.env.GROQ_API_KEY = 'stub-test-key';
process.env.GROQ_BASE_URL = `http://127.0.0.1:${STUB_PORT}`;

const { interpretBrief } = await import('../src/services/interpretService.ts');

const MOCK_INTERPRET_RESPONSE = {
  requirements: {
    project: 'ESP32 DHT22 Monitor',
    intent: 'Monitor temperature and humidity using ESP32 and DHT22.',
    domain: 'iot',
    mechanical: {},
    power: { source: 'usb' },
    constraints: {},
    assumptions: ['Using ESP32 DevKit V1'],
    confidence: 0.8,
  },
  questions: [
    {
      id: 'sampling-rate',
      prompt: 'How often to sample?',
      why: 'Dictates power and flash consumption.',
      impact: 'Changes loop delay.',
      kind: 'number',
      options: [],
      default: '5',
      unit: 's',
    },
  ],
  assumptions: ['Using ESP32 DevKit V1'],
  ready: false,
};

describe('single-round questions guarantee', () => {
  let server;

  before(async () => {
    server = http.createServer((req, res) => {
      let body = '';
      req.on('data', (chunk) => {
        body += chunk;
      });
      req.on('end', () => {
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(
          JSON.stringify({
            choices: [{ message: { content: JSON.stringify(MOCK_INTERPRET_RESPONSE) } }],
          }),
        );
      });
    });

    await new Promise((resolve) => server.listen(STUB_PORT, '127.0.0.1', resolve));
  });

  after(async () => {
    await new Promise((resolve) => server.close(resolve));
  });

  it('first pass returns questions as generated by the model', async () => {
    const result = await interpretBrief({
      brief: 'esp32 and dht22',
      answers: {},
      priorQuestions: [],
      feedback: [],
    });

    assert.equal(result.ready, false);
    assert.equal(result.questions.length, 1);
    assert.equal(result.questions[0].id, 'sampling-rate');
  });

  it('second pass forces ready=true, questions=[], and folds extra questions into assumptions', async () => {
    const priorQuestions = [
      {
        id: 'sampling-rate',
        prompt: 'How often to sample?',
        why: 'Dictates power and flash consumption.',
        impact: 'Changes loop delay.',
        kind: 'number',
        options: [],
        default: '5',
      },
    ];

    const answers = {
      'sampling-rate': '10',
    };

    const result = await interpretBrief({
      brief: 'esp32 and dht22',
      answers,
      priorQuestions,
      feedback: [],
    });

    assert.equal(result.ready, true);
    assert.deepEqual(result.questions, []);
    assert.ok(result.assumptions.some((a) => a.includes('Assumed (no second round):')));
  });
});
