import assert from 'node:assert/strict';
import { after, describe, it } from 'node:test';

import { applyBedrockStubEnv, startBedrockStub } from './bedrockStub.mjs';

const MOCK_INTERPRET_RESPONSE = {
  requirements: {
    project: 'ESP32 DHT22 Monitor',
    intent: 'Monitor temperature and humidity using ESP32 and DHT22.',
    domain: 'iot',
    mechanical: {},
    power: { source: 'usb' },
    constraints: {},
    assumptions: ['Using ESP32 DevKit V1'],
    confidence: 0.8,
  },
  questions: [
    {
      id: 'sampling-rate',
      prompt: 'How often to sample?',
      why: 'Dictates power and flash consumption.',
      impact: 'Changes loop delay.',
      kind: 'number',
      options: [],
      default: '5',
      unit: 's',
    },
  ],
  assumptions: ['Using ESP32 DevKit V1'],
  ready: false,
};

// The stub must exist (and env must point at it) BEFORE llmService/env load.
const stub = await startBedrockStub(() => JSON.stringify(MOCK_INTERPRET_RESPONSE));
applyBedrockStubEnv(stub.port);
process.env.LOG_LEVEL = 'silent';

const { interpretBrief } = await import('../src/services/interpretService.ts');

describe('single-round questions guarantee', () => {
  after(async () => {
    await stub.close();
  });

  it('first pass returns questions as generated by the model', async () => {
    const result = await interpretBrief({
      brief: 'esp32 and dht22',
      answers: {},
      priorQuestions: [],
      feedback: [],
    });

    assert.equal(result.ready, false);
    assert.equal(result.questions.length, 1);
    assert.equal(result.questions[0].id, 'sampling-rate');
  });

  it('second pass forces ready=true, questions=[], and folds extra questions into assumptions', async () => {
    const priorQuestions = [
      {
        id: 'sampling-rate',
        prompt: 'How often to sample?',
        why: 'Dictates power and flash consumption.',
        impact: 'Changes loop delay.',
        kind: 'number',
        options: [],
        default: '5',
      },
    ];

    const answers = {
      'sampling-rate': '10',
    };

    const result = await interpretBrief({
      brief: 'esp32 and dht22',
      answers,
      priorQuestions,
      feedback: [],
    });

    assert.equal(result.ready, true);
    assert.deepEqual(result.questions, []);
    assert.ok(result.assumptions.some((a) => a.includes('Assumed (no second round):')));
  });
});
