import type { FirmwareResult } from '../schemas/build.js';
import type { SimResult } from '../providers/sim/types.js';
import type { Bom } from './bom.js';
import type { DeviceBuildPlan } from './types.js';

/**
 * Per-build assembly + operating instructions.
 *
 * Generated from THIS build's resolved plan — board, every module, the exact
 * pins the planner allocated, the wiring notes from the knowledge base, the
 * sample cadence the human chose and the simulation verdict. Two different
 * device builds therefore produce two genuinely different documents; nothing
 * here is a static template with the name swapped.
 */
export function buildInstructions(input: {
  plan: DeviceBuildPlan;
  firmware: FirmwareResult;
  bom: Bom;
  hardwareSim?: SimResult | null;
  softwareReady: boolean;
  softwareFileCount: number;
  /**
   * §7 export contract: decisions the spec graph made silently on the user's
   * behalf, preserved so the coding agent — and the user — can see what was
   * decided (and override it), not just what was asked.
   */
  specDecisions?: Array<{ node: string; claim: string; why: string }>;
  /** §6 disclosures: real-world variance that never blocked validation. */
  specUncertainties?: Array<{ node: string; note: string }>;
}): string {
  const { plan, firmware, bom, hardwareSim } = input;
  const rupees = (paise: number) => `₹${(paise / 100).toFixed(2)}`;
  const lines: string[] = [];

  lines.push(`# ${plan.projectName} — build instructions`);
  lines.push('');
  lines.push(
    `Generated by Wireup for this build only. Board: **${plan.board.name}** (${plan.board.mcu}, ${plan.board.voltage} V logic). ` +
      `${plan.modules.length} module(s), sampling every ${plan.sampleIntervalMs} ms.`,
  );
  lines.push('');
  lines.push(`> Brief: _${plan.brief.slice(0, 400)}_`);
  lines.push('');

  // 1. Parts
  lines.push('## 1. Parts you need');
  lines.push('');
  lines.push('| Ref | Part | Part number | Qty | Approx price |');
  lines.push('| --- | ---- | ----------- | --- | ------------ |');
  for (const entry of bom.entries) {
    lines.push(
      `| ${entry.ref} | ${entry.name} | \`${entry.partNumber}\` | ${entry.quantity} | ${entry.approxPricePaise ? rupees(entry.approxPricePaise) : '—'} |`,
    );
  }
  lines.push('');
  lines.push(
    `Approximate parts cost: **${rupees(bom.totalApproxPaise)}**${bom.incomplete ? ' (some prices unknown — check the purchase links in the app)' : ''}.`,
  );
  lines.push('');

  // 2. Wiring
  lines.push('## 2. Wiring');
  lines.push('');
  lines.push('| Module | Signal | Pin on ' + plan.board.name + ' |');
  lines.push('| ------ | ------ | ------ |');
  for (const module of plan.modules) {
    for (const [role, pin] of Object.entries(module.pins)) {
      lines.push(`| ${module.name} | ${role} | \`${pin}\` |`);
    }
    lines.push(`| ${module.name} | VCC | \`3V3\` |`);
    lines.push(`| ${module.name} | GND | \`GND\` |`);
  }
  lines.push('');
  const wiringNotes = plan.modules.flatMap((module) =>
    module.wiringNotes.map((note) => `- **${module.name}** — ${note}`),
  );
  if (wiringNotes.length > 0) {
    lines.push('### Wiring notes from the datasheets');
    lines.push('');
    lines.push(...wiringNotes);
    lines.push('');
  }

  // 3. Flashing
  lines.push('## 3. Flash the firmware');
  lines.push('');
  lines.push(`Firmware: ${firmware.files.length} file(s), ${firmware.language} on ${firmware.framework}, board \`${firmware.board}\`.`);
  lines.push('');
  firmware.buildSteps.forEach((step, index) => lines.push(`${index + 1}. ${step}`));
  lines.push('');
  if (plan.wifi.configured) {
    lines.push(`Wi-Fi SSID \`${plan.wifi.ssid}\` is already written into \`firmware/config.h\`.`);
  } else {
    lines.push('Open `firmware/config.h` and set your Wi-Fi SSID and password before flashing.');
  }
  lines.push('');

  // 4. The dashboard
  lines.push('## 4. Run the dashboard');
  lines.push('');
  lines.push(`The software zip contains ${input.softwareFileCount} file(s) — an Express API plus a React dashboard.`);
  lines.push('');
  lines.push('```bash');
  lines.push('npm install');
  lines.push('npm run dev');
  lines.push('```');
  lines.push('');
  lines.push(
    plan.webServer
      ? 'The device also serves its own dashboard at `http://<device-ip>/` — the software zip only adds long-term history.'
      : 'This build has no on-device web server; the dashboard polls the device API directly.',
  );
  lines.push('');

  // 5. What to expect
  lines.push('## 5. What you should see');
  lines.push('');
  for (const module of plan.modules) {
    for (const metric of module.metrics) {
      lines.push(
        `- \`${metric.jsonField}\` — ${metric.label} in ${metric.unit}` +
          (metric.min !== undefined && metric.max !== undefined ? ` (valid range ${metric.min}…${metric.max})` : ''),
      );
    }
    for (const control of module.controls) {
      lines.push(`- control \`${control.jsonField}\` — ${control.label} (${control.kind})`);
    }
  }
  lines.push('');

  // 6. Verification record
  lines.push('## 6. Verification for this build');
  lines.push('');
  lines.push(`- Software gate (npm · tsc · vite · contract): **${input.softwareReady ? 'passed' : 'FAILED'}**`);
  if (hardwareSim) {
    lines.push(
      `- Hardware simulation (${hardwareSim.provider}): **${hardwareSim.errored ? 'PROVIDER ERROR' : hardwareSim.ok ? 'passed' : 'FAILED'}** — ${hardwareSim.checks.length} check(s) in ${(hardwareSim.durationMs / 1000).toFixed(1)} s`,
    );
    for (const check of hardwareSim.checks.filter((c) => !c.ok)) {
      lines.push(`  - ✘ ${check.name}: ${check.detail}`);
    }
  } else {
    lines.push('- Hardware simulation: not run.');
  }
  lines.push('');

  // 7. Troubleshooting drawn from this plan's firmware notes.
  const firmwareNotes = plan.modules.flatMap((module) =>
    module.firmwareNotes.map((note) => `- **${module.name}** — ${note}`),
  );
  if (firmwareNotes.length > 0) {
    lines.push('## 7. Troubleshooting');
    lines.push('');
    lines.push(...firmwareNotes);
    lines.push('');
  }

  // 8. Spec-graph decisions made on the user's behalf (§7 export contract).
  if (input.specDecisions && input.specDecisions.length > 0) {
    lines.push('## 8. Decisions made on your behalf');
    lines.push('');
    lines.push(
      'The spec graph resolved these forks silently — every one is a recorded assumption you can override on the spec-graph page:',
    );
    lines.push('');
    for (const decision of input.specDecisions) {
      lines.push(`- **${decision.node}** — ${decision.claim} _(${decision.why})_`);
    }
    lines.push('');
  }

  // 9. Known real-world uncertainties — disclosed, never blocking (§6).
  if (input.specUncertainties && input.specUncertainties.length > 0) {
    lines.push('## 9. Known real-world uncertainties (non-blocking)');
    lines.push('');
    lines.push(
      'The spec is internally consistent and complete enough to build from; these are the parts no amount of spec-writing can pin down — expect field tuning:',
    );
    lines.push('');
    for (const entry of input.specUncertainties) {
      lines.push(`- **${entry.node}** — ${entry.note}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}
