/**
 * Deterministic software (MERN dashboard) synthesiser.
 *
 * Merges the committed Wireup MERN scaffold with the device wiring derived
 * from the resolved build plan:
 *   - frontend/src/lib/deviceSpec.ts       ← metrics/controls from the KB
 *   - backend/src/config/deviceEndpoints.ts← routes the firmware actually serves
 *   - .env.example (+ .env)                ← local-network defaults
 *   - README.md                            ← device-specific runbook
 *
 * Every id cross-checks firmware ↔ backend ↔ frontend before validation.
 */

import type { BuildFile, WebsiteRequirements } from '../schemas/build.js';
import { loadScaffold } from '../services/scaffoldService.js';
import type { DeviceBuildPlan, ResolvedModule } from './types.js';

export interface SoftwareSynthResult {
  files: BuildFile[];
  requirements: WebsiteRequirements;
  envExampleLines: string[];
  readme: string;
}

function tsString(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function renderDeviceSpec(plan: DeviceBuildPlan, fieldOverrides: Record<string, string> = {}): string {
  const metricEntries = plan.modules.flatMap((module) =>
    module.metrics.map((metric) => {
      const field = fieldOverrides[metric.id] ?? metric.jsonField;
      const minMax =
        metric.min !== undefined && metric.max !== undefined
          ? `\n    min: ${metric.min},\n    max: ${metric.max},`
          : '';
      return `  {
    id: ${tsString(metric.id)},
    label: ${tsString(metric.label)},
    unit: ${tsString(metric.unit)},
    path: ${tsString(`${metric.id}.${field}`)},
    numeric: true,${minMax}
  },`;
    }),
  );

  const controlEntries = plan.modules.flatMap((module) =>
    module.controls.map((control) => {
      const options =
        control.kind === 'select'
          ? `\n    options: [${((control.command.options as string[]) ?? [])
              .map((opt) => `{ value: '${opt}', label: '${opt}°' }`)
              .join(', ')}],`
          : control.kind === 'toggle'
            ? `\n    options: [\n      { value: 'on', label: 'On' },\n      { value: 'off', label: 'Off' },\n    ],`
            : '';
      // For toggle controls the dashboard sends { state: <choice> }; selects send their field.
      const field = (control.command.field as string) ?? 'state';
      return `  {
    id: ${tsString(control.id)},
    label: ${tsString(control.label)},
    kind: '${control.kind}',${options}
    command: { ${field}: true },
  },`;
    }),
  );

  return `/**
 * [WIREUP GENERATED] Device definition the dashboard renders from.
 *
 * Project: ${plan.projectName}
 * The UI is fully data-driven: each metric below becomes a live card, each
 * control a button/toggle. Regenerate via Wireup to change the device.
 */

export interface DeviceMetric {
  id: string; // matches backend readEndpoint id
  label: string;
  unit: string;
  /** How to read the numeric value off the device payload. */
  path: string;
  numeric: boolean;
  min?: number;
  max?: number;
}

export interface DeviceControl {
  id: string; // matches backend controlEndpoint id
  label: string;
  kind: 'toggle' | 'select' | 'button';
  options?: { value: string; label: string }[];
  command: Record<string, unknown>;
}

export interface DeviceSpec {
  name: string;
  tagline: string;
  metrics: DeviceMetric[];
  controls: DeviceControl[];
  refreshMs: number;
  statusPath: string;
}

export const deviceSpec: DeviceSpec = {
  name: ${tsString(plan.projectName)},
  tagline: 'Live dashboard · generated by Wireup',
  metrics: [
${metricEntries.join('\n')}
  ],
  controls: [
${controlEntries.join('\n')}
  ],
  refreshMs: ${plan.sampleIntervalMs},
  statusPath: 'status.state',
};
`;
}

function renderDeviceEndpoints(plan: DeviceBuildPlan): string {
  const reads: string[] = [];

  // One read endpoint per metric — all backed by the firmware's /api/sensors
  // route, plus the canonical status endpoint for the header badge.
  for (const module of plan.modules) {
    for (const metric of module.metrics) {
      reads.push(`  {
    id: ${tsString(metric.id)},
    label: ${tsString(metric.label)},
    path: '/api/sensors',
    method: 'GET',
    kind: 'json',
    unit: ${tsString(metric.unit)},
    // The exact JSON key this metric reads off the device payload — used to
    // extract a number for history instead of storing the whole payload.
    field: ${tsString(metric.jsonField)},
  },`);
    }
  }
  reads.push(`  {
    id: 'status',
    label: 'Status',
    path: '/api/status',
    method: 'GET',
    kind: 'json',
  },`);

  const controls = plan.modules.flatMap((module) =>
    module.controls.map(
      (control) => `  {
    id: ${tsString(control.id)},
    label: ${tsString(control.label)},
    path: '/api/control/${control.id}',
    method: 'POST',
    kind: 'json',
    payload: true,
  },`,
    ),
  );

  return `import { env } from './env.js';

/**
 * [WIREUP GENERATED] How the backend reaches the device.
 *
 * Project: ${plan.projectName} · Board: ${plan.board.name}
 * Paths resolve against \`\${DEVICE_PROTOCOL}://\${DEVICE_IP}:\${DEVICE_PORT}\`.
 * These routes are exactly what the generated firmware exposes.
 */

export interface DeviceEndpoint {
  id: string;
  label: string;
  path: string;
  method: 'GET' | 'POST' | 'PUT';
  kind: 'text' | 'json';
  unit?: string;
  payload?: boolean;
  /** JSON key inside the payload this metric reads (for history extraction). */
  field?: string;
}

export function deviceBaseUrl(): string {
  const host = env.DEVICE_IP || env.DEVICE_HOST || '192.168.1.100';
  return \`\${env.DEVICE_PROTOCOL}://\${host}:\${env.DEVICE_PORT}\`;
}

export function readEndpoints(): DeviceEndpoint[] {
  return defaultReadEndpoints;
}

export function controlEndpoints(): DeviceEndpoint[] {
  return defaultControlEndpoints;
}

export function deviceInfo(): Record<string, string> {
  return {
    name: ${tsString(plan.slug)},
    firmware: 'wireup-firmware-1.0.0',
    transport: 'http-lan',
    board: ${tsString(plan.board.name)},
  };
}

const defaultReadEndpoints: DeviceEndpoint[] = [
${reads.join('\n')}
];

const defaultControlEndpoints: DeviceEndpoint[] = [
${controls.join('\n')}
];
`;
}

function renderWebsiteRequirements(plan: DeviceBuildPlan): WebsiteRequirements {
  const modulesSensors: ResolvedModule[] = plan.modules.filter((m) => m.metrics.length > 0);
  const modulesActuators: ResolvedModule[] = plan.modules.filter((m) => m.controls.length > 0);
  return {
    requested: plan.webServer,
    summary: plan.webServer
      ? `Local-network dashboard for ${plan.projectName}: live readings from ${plan.modules.length} module(s) over HTTP, reachable from any computer on the same network.`
      : 'No web access requested in the brief — firmware only.',
    device: {
      name: plan.slug,
      connection: 'wifi',
      localIpHint: 'printed by the firmware over Serial (or 192.168.4.1 in fallback AP mode)',
      port: 80,
      protocol: 'http',
      endpointBase: '',
      ssidHint: plan.wifi.configured ? plan.wifi.ssid : null,
      credentialsRequired: false,
    },
    readEndpoints: modulesSensors.flatMap((module) =>
      module.metrics.map((metric) => ({
        name: metric.label,
        path: '/api/sensors',
        method: 'GET' as const,
        description: `${metric.jsonField} from ${module.name}`,
        dataType: 'number',
        unit: metric.unit,
        sampleIntervalMs: plan.sampleIntervalMs,
      })),
    ),
    controlEndpoints: modulesActuators.flatMap((module) =>
      module.controls.map((control) => ({
        name: control.label,
        path: `/api/control/${control.id}`,
        method: 'POST' as const,
        description: `Toggle/actuate ${control.label}`,
        bodyType: 'form/query arg "state"',
        commandOptions: ['on', 'off'],
      })),
    ),
    telemetry: {
      livePath: '/api/telemetry/live',
      historyPath: '/api/telemetry/history',
      sampleRateMs: plan.sampleIntervalMs,
      retentionDays: 7,
    },
    dataModel: plan.modules.flatMap((module) =>
      module.metrics.map((metric) => ({
        field: metric.jsonField,
        type: 'number',
        unit: metric.unit,
        source: module.name,
      })),
    ),
    security: ['Payloads are local-network only (no cloud dependency).', 'Firmware sends permissive CORS for LAN dashboards.'],
    notes: plan.wifi.configured
      ? [`Wi-Fi SSID "${plan.wifi.ssid}" baked into firmware/config.h — re-flash to change.`]
      : ['Set WIFI_SSID / WIFI_PASSWORD in firmware/config.h before flashing.'],
  };
}

const SCAFFOLD_REPLACEMENTS = new Map<string, (plan: DeviceBuildPlan, fieldOverrides: Record<string, string>) => string>([
  ['frontend/src/lib/deviceSpec.ts', renderDeviceSpec],
  ['backend/src/config/deviceEndpoints.ts', renderDeviceEndpoints],
]);

function renderRootReadme(plan: DeviceBuildPlan): string {
  return `# ${plan.projectName} — local monitoring software (MERN)

Generated by **Wireup** to pair with the \`${plan.slug}\` firmware zip.
Runs entirely on your computer and your local network — no cloud account,
no external service.

## Quick start

\`\`\`bash
# 1. Backend (terminal 1)
cd backend
cp .env.example .env      # then set DEVICE_IP to the address the firmware printed
npm install
npm run dev               # http://localhost:8080

# 2. Frontend (terminal 2)
cd frontend
npm install
npm run dev               # http://localhost:5173
\`\`\`

Open **http://localhost:5173** — live cards for every sensor appear as soon
as the board is reachable.

## How it fits together

\`\`\`
${plan.board.name}  ──Wi-Fi──▶  this MERN app  ──▶  your browser
 ${plan.modules.map((m) => m.partNumber).join(', ')}     Express proxy          React dashboard
\`\`\`

- The **firmware** (other zip) serves \`/api/sensors\` + \`/api/status\` JSON.
- The **backend** (\`backend/\`) proxies those routes, records history
  (MongoDB if \`MONGO_URI\` is set, in-memory otherwise) and serves
  \`/api/telemetry/live\`.
- The **frontend** (\`frontend/\`) renders the dashboard from
  \`frontend/src/lib/deviceSpec.ts\` — fully data-driven.

## Device endpoints used

| Route on device | Purpose |
| --- | --- |
| \`GET /api/sensors\` | all live readings |
| \`GET /api/status\` | health, IP, RSSI |
${plan.modules
  .flatMap((m) => m.controls.map((c) => `| \`POST /api/control/${c.id}\` | ${c.label} |`))
  .join('\n')}

_Troubleshooting: if the dashboard says "device unreachable", confirm
\`DEVICE_IP\` in \`backend/.env\` matches what the Serial monitor printed, and
that your computer and the board share a network (or connect your computer to
the board's own \`${plan.slug}\` hotspot)._
`;
}

/**
 * Merge scaffold + generated wiring into the final software tree.
 *
 * `fieldOverrides` re-points a metric id at a JSON field the firmware actually
 * publishes (e.g. the LLM draft emits `temperature` while the KB calls it
 * `temperature_c`). Omit to use the knowledge-base fields — the deterministic
 * firmware publishes exactly those.
 */
export async function synthesizeSoftware(
  plan: DeviceBuildPlan,
  fieldOverrides: Record<string, string> = {},
): Promise<SoftwareSynthResult> {
  const scaffold = await loadScaffold();
  const envExampleLines = [
    'PORT=8080',
    // Wide-open origins: the dashboard is for every computer/phone on your
    // LAN, not just the machine that runs it. The API holds no secrets.
    'CORS_ORIGIN=*',
    '',
    '# The device the firmware zip produces. Flash it, watch Serial, fill this in.',
    'DEVICE_PROTOCOL=http',
    '# Option A (recommended): mDNS hostname — macOS/Linux work out of the box,',
    '# Windows needs Bonjour installed. Printed by the firmware as <slug>.local',
    `DEVICE_HOST=${plan.slug}.local`,
    '# Option B: the IP the firmware printed on Serial. Wins over DEVICE_HOST.',
    '# DEVICE_IP=192.168.1.50',
    'DEVICE_PORT=80',
    'DEVICE_TIMEOUT_MS=4000',
    '',
    '# Optional: persist history (otherwise kept in memory).',
    '# MONGO_URI=mongodb://localhost:27017/wireup-device',
  ];

  const files: BuildFile[] = [];
  for (const file of scaffold) {
    const replacement = SCAFFOLD_REPLACEMENTS.get(file.path);
    if (replacement) {
      files.push({ path: file.path, content: replacement(plan, fieldOverrides) });
      continue;
    }
    if (file.path === 'backend/.env.example') {
      files.push({ path: file.path, content: `${envExampleLines.join('\n')}\n` });
      continue;
    }
    files.push({ ...file, content: file.content.replaceAll('{project-name}', plan.slug) });
  }

  // Friendly extras.
  files.push({ path: 'backend/.env', content: `${envExampleLines.join('\n')}\n` });
  files.push({ path: 'README.md', content: renderRootReadme(plan) });

  return {
    files,
    requirements: renderWebsiteRequirements(plan),
    envExampleLines,
    readme: renderRootReadme(plan),
  };
}
